### PR TITLE
issue 53 fix game window size

### LINKED ISSUE #53: Fix Game Window Size
-Chessboard is current off-center
-Determine what size we want all of the screens to be

### PR DESCRIPTION
**Pull request by torin99r**
this adjusts the sizes for the background images and all screens
to have it be all matching
closes #53

### CODE REVIEW

File: chessGame/src/main/java/edu/se181/FindGameScreen.kt [hunk 1]
```diff
@@ -66,7 +66,7 @@ class FindGameScreen {
                 } else {
                     val joinGame = FindGameSceenDialogs.joinGameDialog()
                     if (joinGame == YES) {
-                        //joinGame
+                        GameStage.launch()
```
Comment (gilllian) [inline chessGame/src/main/java/edu/se181/FindGameScreen.kt:69]: not supposed to be in right now
